# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.

default:
  image: python:3.5
  tags: 
    - docker

  before_script:
  - python --version  # For debugging
  - pip install virtualenv
  - virtualenv /venv
  - source /venv/bin/activate

stages:
  - test
  - install

test:
  stage: test
  script:
    - python -m unittest

lint:
  stage: test
  script:
    - pip install flake8
    - flake8
#    - pip install tox flake8  # you can also use tox
#    - tox -e py36,flake8
